packages:
  - packages/**

catalog:
  "@types/node": "20.x"
  workspace-tools: ^0.38.1
  vscode-languageserver: ^9.0.1
  vscode-languageserver-textdocument: ^1.0.12
  vscode-languageclient: ^9.0.0
  typescript: 5.7.3
  prettier: 3.4.2
  yaml: 2.4.5
  coc.nvim: ^0.0.83-next.18
  esbuild: ^0.24.0
  tsup: 8.3.5
